apiVersion: v1
kind: Service
metadata:
  name: {{ include "dependency.fullname" . }}
  labels:
    {{- include "dependency.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: express
  selector:
    {{- include "dependency.selectorLabels" . | nindent 4 }}
